// packages/vue/src/LockBadge.vue
<script setup lang="ts">
const props = defineProps<{ ownerId: string; class?: string }>()
</script>

<template>
  <span>
    <span
      v-if="props.ownerId"
      :class="['ensemble-lock-badge', props.class]"
      :title="`${props.ownerId} is editing this cell`"
      style="display: inline-block; padding: 2px 6px; background: #fef3c7; border: 1px solid #fbbf24; border-radius: 4px; font-size: 11px; color: #92400e"
    >
      {{ props.ownerId }} editing
    </span>
  </span>
</template>

// packages/react/src/LockBadge.tsx
export interface LockBadgeProps {
  ownerId: string
  className?: string
}

export function LockBadge({ ownerId, className }: LockBadgeProps) {
  if (!ownerId) return null
  return (
    <span
      className={`ensemble-lock-badge ${className ?? ''}`}
      style={{
        display: 'inline-block',
        padding: '2px 6px',
        background: '#fef3c7',
        border: '1px solid #fbbf24',
        borderRadius: 4,
        fontSize: 11,
        color: '#92400e',
      }}
      title={`${ownerId} is editing this cell`}
    >
      {ownerId} editing
    </span>
  )
}
