// packages/vue/src/VersionHistoryPanel.vue
<script setup lang="ts">
import type { ApiClient, Version } from '@ensemble-sheets/core'
import { onMounted, ref } from 'vue'

const props = defineProps<{
  api: Pick<ApiClient, 'listVersions' | 'createVersion' | 'restoreVersion'>
  workbookId: string
}>()
const emit = defineEmits<{ restored: [] }>()

const items = ref<Version[]>([])
const creating = ref(false)
const draftName = ref('')

async function refresh() {
  const { items: list } = await props.api.listVersions(props.workbookId)
  items.value = list
}
async function submit() {
  if (!draftName.value.trim()) return
  await props.api.createVersion(props.workbookId, draftName.value)
  creating.value = false
  draftName.value = ''
  await refresh()
}
async function restore(versionId: string) {
  await props.api.restoreVersion(props.workbookId, versionId)
  emit('restored')
}
onMounted(refresh)
</script>

<template>
  <div class="ensemble-version-history">
    <header style="display: flex; gap: 8px; align-items: center">
      <strong>Version history</strong>
      <button aria-label="Save version" @click="creating = true">+</button>
    </header>
    <form v-if="creating" @submit.prevent="submit">
      <input v-model="draftName" aria-label="Version name" autofocus />
    </form>
    <ul>
      <li v-for="v in items" :key="v.id" style="display: flex; gap: 12px; align-items: center">
        <span>{{ v.name }}</span>
        <button @click="restore(v.id)">Restore</button>
      </li>
    </ul>
  </div>
</template>

// packages/react/src/VersionHistoryPanel.tsx
import type { ApiClient, Version } from '@ensemble-sheets/core'
import { useCallback, useEffect, useState } from 'react'

export interface VersionHistoryPanelProps {
  api: Pick<ApiClient, 'listVersions' | 'createVersion' | 'restoreVersion'>
  workbookId: string
  onRestore?: () => void
}

export function VersionHistoryPanel({ api, workbookId, onRestore }: VersionHistoryPanelProps) {
  const [items, setItems] = useState<Version[]>([])
  const [creating, setCreating] = useState(false)
  const [draftName, setDraftName] = useState('')

  const refresh = useCallback(async () => {
    const { items } = await api.listVersions(workbookId)
    setItems(items)
  }, [api, workbookId])

  useEffect(() => { void refresh() }, [refresh])

  return (
    <div className="ensemble-version-history">
      <header style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
        <strong>Version history</strong>
        <button aria-label="Save version" onClick={() => setCreating(true)}>+</button>
      </header>
      {creating && (
        <form onSubmit={async (e) => {
          e.preventDefault()
          if (!draftName.trim()) return
          await api.createVersion(workbookId, draftName)
          setCreating(false); setDraftName('')
          await refresh()
        }}>
          <input aria-label="Version name" value={draftName}
                 onChange={(e) => setDraftName(e.target.value)} autoFocus />
        </form>
      )}
      <ul>
        {items.map((v) => (
          <li key={v.id} style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
            <span>{v.name}</span>
            <button onClick={async () => { await api.restoreVersion(workbookId, v.id); onRestore?.() }}>
              Restore
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
